all: Calc LectureArg Triangle

Calc:
	gcc -Wall -Wfatal-errors -o Calc Calc.c

LectureArg:
	gcc -Wall -Wfatal-errors -o LectureArg LectureArg.c

Triangle:
	gcc -Wall -Wfatal-errors -o Triangle Triangle.c

clean:
	rm Calc LectureArg Triangle
	rm '*.o' '*.out'